/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package calculadora;

import java.awt.Cursor;
import javax.swing.JOptionPane;

/**
 *
 * @author Montenegro
 */
public class Interfaz_Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz_Calculadora
     */
    public Interfaz_Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_num_1 = new javax.swing.JButton();
        btn_num_2 = new javax.swing.JButton();
        btn_num_3 = new javax.swing.JButton();
        btn_num_4 = new javax.swing.JButton();
        btn_num_5 = new javax.swing.JButton();
        btn_num_6 = new javax.swing.JButton();
        btn_num_7 = new javax.swing.JButton();
        btn_num_8 = new javax.swing.JButton();
        btn_num_9 = new javax.swing.JButton();
        btn_num_0 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btn_suma = new javax.swing.JButton();
        btn_resta = new javax.swing.JButton();
        btn_multi = new javax.swing.JButton();
        btn_div = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_val1 = new javax.swing.JTextField();
        txt_val2 = new javax.swing.JTextField();
        txt_resultado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 204, 255));

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        btn_num_1.setBackground(new java.awt.Color(0, 0, 255));
        btn_num_1.setForeground(new java.awt.Color(0, 0, 102));
        btn_num_1.setText("1");
        btn_num_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_num_1ActionPerformed(evt);
            }
        });

        btn_num_2.setBackground(new java.awt.Color(0, 0, 255));
        btn_num_2.setForeground(new java.awt.Color(0, 0, 102));
        btn_num_2.setText("2");
        btn_num_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_num_2ActionPerformed(evt);
            }
        });

        btn_num_3.setBackground(new java.awt.Color(0, 0, 255));
        btn_num_3.setForeground(new java.awt.Color(0, 0, 102));
        btn_num_3.setText("3");
        btn_num_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_num_3ActionPerformed(evt);
            }
        });

        btn_num_4.setBackground(new java.awt.Color(0, 0, 255));
        btn_num_4.setForeground(new java.awt.Color(0, 0, 102));
        btn_num_4.setText("4");
        btn_num_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_num_4ActionPerformed(evt);
            }
        });

        btn_num_5.setBackground(new java.awt.Color(0, 0, 255));
        btn_num_5.setForeground(new java.awt.Color(0, 0, 102));
        btn_num_5.setText("5");
        btn_num_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_num_5ActionPerformed(evt);
            }
        });

        btn_num_6.setBackground(new java.awt.Color(0, 0, 255));
        btn_num_6.setForeground(new java.awt.Color(0, 0, 102));
        btn_num_6.setText("6");
        btn_num_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_num_6ActionPerformed(evt);
            }
        });

        btn_num_7.setBackground(new java.awt.Color(0, 0, 255));
        btn_num_7.setForeground(new java.awt.Color(0, 0, 102));
        btn_num_7.setText("7");
        btn_num_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_num_7ActionPerformed(evt);
            }
        });

        btn_num_8.setBackground(new java.awt.Color(0, 0, 255));
        btn_num_8.setForeground(new java.awt.Color(0, 0, 102));
        btn_num_8.setText("8");
        btn_num_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_num_8ActionPerformed(evt);
            }
        });

        btn_num_9.setBackground(new java.awt.Color(0, 0, 255));
        btn_num_9.setForeground(new java.awt.Color(0, 0, 102));
        btn_num_9.setText("9");
        btn_num_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_num_9ActionPerformed(evt);
            }
        });

        btn_num_0.setBackground(new java.awt.Color(0, 0, 255));
        btn_num_0.setForeground(new java.awt.Color(0, 0, 102));
        btn_num_0.setText("0");
        btn_num_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_num_0ActionPerformed(evt);
            }
        });

        btn_suma.setBackground(new java.awt.Color(0, 0, 255));
        btn_suma.setForeground(new java.awt.Color(0, 0, 102));
        btn_suma.setText("+");
        btn_suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sumaActionPerformed(evt);
            }
        });

        btn_resta.setBackground(new java.awt.Color(0, 0, 255));
        btn_resta.setForeground(new java.awt.Color(0, 0, 102));
        btn_resta.setText("-");
        btn_resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_restaActionPerformed(evt);
            }
        });

        btn_multi.setBackground(new java.awt.Color(0, 0, 255));
        btn_multi.setForeground(new java.awt.Color(0, 0, 102));
        btn_multi.setText("*");
        btn_multi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_multiActionPerformed(evt);
            }
        });

        btn_div.setBackground(new java.awt.Color(0, 0, 255));
        btn_div.setForeground(new java.awt.Color(0, 0, 102));
        btn_div.setText("/");
        btn_div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_divActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_multi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_suma, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_resta, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(btn_div, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_suma, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_resta, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_multi, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_div, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel1.setText("Valor 1:");

        jLabel2.setText("Valor 2:");

        jLabel3.setText("Resultado:");

        txt_val1.setBackground(new java.awt.Color(0, 0, 102));
        txt_val1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_val1.setForeground(new java.awt.Color(255, 255, 255));
        txt_val1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_val1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_val1FocusLost(evt);
            }
        });
        txt_val1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_val1KeyTyped(evt);
            }
        });

        txt_val2.setBackground(new java.awt.Color(0, 0, 102));
        txt_val2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_val2.setForeground(new java.awt.Color(255, 255, 255));
        txt_val2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_val2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_val2FocusLost(evt);
            }
        });

        txt_resultado.setBackground(new java.awt.Color(0, 0, 102));
        txt_resultado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_resultado.setForeground(new java.awt.Color(255, 255, 255));
        txt_resultado.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_num_0, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_num_4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_num_5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_num_6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_num_7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_num_8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_num_9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_num_1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_num_2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_num_3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_val2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_val1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_val1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_val2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txt_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_num_1)
                            .addComponent(btn_num_2)
                            .addComponent(btn_num_3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_num_4)
                            .addComponent(btn_num_5)
                            .addComponent(btn_num_6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_num_7)
                            .addComponent(btn_num_8)
                            .addComponent(btn_num_9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_num_0)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int cursor=0;
    String val="";
    int posicion=0;
    private void txt_val1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_val1FocusLost
        // TODO add your handling code here:
        cursor=0;
        posicion=txt_val1.getCaretPosition();
    }//GEN-LAST:event_txt_val1FocusLost

    private void txt_val2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_val2FocusLost
        // TODO add your handling code here:
        cursor=1;
        posicion=txt_val2.getCaretPosition();
    }//GEN-LAST:event_txt_val2FocusLost

        Operaciones op= new Operaciones();
    private void btn_num_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_num_1ActionPerformed
        // TODO add your handling code here:
        val="1";
         if(cursor==0){
            txt_val1.setText(op.insertar(val,txt_val1.getText(),posicion));
            txt_val1.requestFocus();            
         }else{
            txt_val2.setText(op.insertar(val,txt_val2.getText(),posicion));
            txt_val2.requestFocus();    
        }
        
    }//GEN-LAST:event_btn_num_1ActionPerformed

    private void btn_num_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_num_2ActionPerformed
        // TODO add your handling code here:
        val="2";
         if(cursor==0){
            txt_val1.setText(op.insertar(val,txt_val1.getText(),posicion));
            txt_val1.requestFocus();            
         }else{
            txt_val2.setText(op.insertar(val,txt_val2.getText(),posicion));
            txt_val2.requestFocus();    
        }
    }//GEN-LAST:event_btn_num_2ActionPerformed

    private void btn_num_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_num_3ActionPerformed
        // TODO add your handling code here:
        val="3";
         if(cursor==0){
            txt_val1.setText(op.insertar(val,txt_val1.getText(),posicion));
            txt_val1.requestFocus();            
         }else{
            txt_val2.setText(op.insertar(val,txt_val2.getText(),posicion));
            txt_val2.requestFocus();    
        }
    }//GEN-LAST:event_btn_num_3ActionPerformed

    private void btn_num_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_num_4ActionPerformed
        // TODO add your handling code here:
        val="4";
         if(cursor==0){
            txt_val1.setText(op.insertar(val,txt_val1.getText(),posicion));
            txt_val1.requestFocus();            
         }else{
            txt_val2.setText(op.insertar(val,txt_val2.getText(),posicion));
            txt_val2.requestFocus();    
        }
    }//GEN-LAST:event_btn_num_4ActionPerformed

    private void btn_num_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_num_5ActionPerformed
        // TODO add your handling code here:
        val="5";
         if(cursor==0){
            txt_val1.setText(op.insertar(val,txt_val1.getText(),posicion));
            txt_val1.requestFocus();            
         }else{
            txt_val2.setText(op.insertar(val,txt_val2.getText(),posicion));
            txt_val2.requestFocus();    
        }
    }//GEN-LAST:event_btn_num_5ActionPerformed

    private void btn_num_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_num_6ActionPerformed
        // TODO add your handling code here:
        val="6";
         if(cursor==0){
            txt_val1.setText(op.insertar(val,txt_val1.getText(),posicion));
            txt_val1.requestFocus();            
         }else{
            txt_val2.setText(op.insertar(val,txt_val2.getText(),posicion));
            txt_val2.requestFocus();    
        }
    }//GEN-LAST:event_btn_num_6ActionPerformed

    private void btn_num_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_num_7ActionPerformed
        // TODO add your handling code here:
        val="7";
         if(cursor==0){
            txt_val1.setText(op.insertar(val,txt_val1.getText(),posicion));
            txt_val1.requestFocus();            
         }else{
            txt_val2.setText(op.insertar(val,txt_val2.getText(),posicion));
            txt_val2.requestFocus();    
        }
    }//GEN-LAST:event_btn_num_7ActionPerformed

    private void btn_num_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_num_9ActionPerformed
        // TODO add your handling code here:
        val="9";
         if(cursor==0){
            txt_val1.setText(op.insertar(val,txt_val1.getText(),posicion));
            txt_val1.requestFocus();            
         }else{
            txt_val2.setText(op.insertar(val,txt_val2.getText(),posicion));
            txt_val2.requestFocus();    
        }
    }//GEN-LAST:event_btn_num_9ActionPerformed

    private void btn_num_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_num_8ActionPerformed
        // TODO add your handling code here:
        val="8";
         if(cursor==0){
            txt_val1.setText(op.insertar(val,txt_val1.getText(),posicion));
            txt_val1.requestFocus();            
         }else{
            txt_val2.setText(op.insertar(val,txt_val2.getText(),posicion));
            txt_val2.requestFocus();    
        }
    }//GEN-LAST:event_btn_num_8ActionPerformed

    private void btn_num_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_num_0ActionPerformed
        // TODO add your handling code here:
        val="0";
         if(cursor==0){
            txt_val1.setText(op.insertar(val,txt_val1.getText(),posicion));
            txt_val1.requestFocus();            
         }else{
            txt_val2.setText(op.insertar(val,txt_val2.getText(),posicion));
            txt_val2.requestFocus();    
        }
    }//GEN-LAST:event_btn_num_0ActionPerformed

    private void txt_val1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_val1KeyTyped
        // TODO add your handling code here:
         char c=evt.getKeyChar();
          if(Character.isLetter(c)) {
              getToolkit().beep();
              evt.consume();
              JOptionPane.showMessageDialog(rootPane,"Caracter no valido","Error", 0);
              
          } 
    }//GEN-LAST:event_txt_val1KeyTyped

    private void btn_sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sumaActionPerformed
        // TODO add your handling code here:
        if(!txt_val1.getText().equals("") || !txt_val2.getText().equals("")){
            txt_resultado.setText(String.valueOf(op.suma(Integer.valueOf(txt_val1.getText()),Integer.valueOf(txt_val2.getText()))));
        }else {
            JOptionPane.showMessageDialog(rootPane,"Faltan valores","Error", 1);
        }
    }//GEN-LAST:event_btn_sumaActionPerformed

    private void btn_restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_restaActionPerformed
        // TODO add your handling code here:
        if(!txt_val1.getText().equals("") || !txt_val2.getText().equals("")){
            txt_resultado.setText(String.valueOf(op.resta(Integer.valueOf(txt_val1.getText()),Integer.valueOf(txt_val2.getText()))));
        }else {
            JOptionPane.showMessageDialog(rootPane,"Faltan valores","Error", 1);
        }
    }//GEN-LAST:event_btn_restaActionPerformed

    private void btn_multiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_multiActionPerformed
        // TODO add your handling code here:
        if(!txt_val1.getText().equals("") || !txt_val2.getText().equals("")){
            txt_resultado.setText(String.valueOf(op.multiplicacion(Integer.valueOf(txt_val1.getText()),Integer.valueOf(txt_val2.getText()))));
        }else {
            JOptionPane.showMessageDialog(rootPane,"Faltan valores","Error", 1);
        }
    }//GEN-LAST:event_btn_multiActionPerformed

    private void btn_divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_divActionPerformed
        // TODO add your handling code here:
        if(!txt_val1.getText().equals("") || !txt_val2.getText().equals("")){
            txt_resultado.setText(String.valueOf(op.division(Integer.valueOf(txt_val1.getText()),Integer.valueOf(txt_val2.getText()))));
        }else {
            JOptionPane.showMessageDialog(rootPane,"Faltan valores","Error", 1);
        }
    }//GEN-LAST:event_btn_divActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_div;
    private javax.swing.JButton btn_multi;
    private javax.swing.JButton btn_num_0;
    private javax.swing.JButton btn_num_1;
    private javax.swing.JButton btn_num_2;
    private javax.swing.JButton btn_num_3;
    private javax.swing.JButton btn_num_4;
    private javax.swing.JButton btn_num_5;
    private javax.swing.JButton btn_num_6;
    private javax.swing.JButton btn_num_7;
    private javax.swing.JButton btn_num_8;
    private javax.swing.JButton btn_num_9;
    private javax.swing.JButton btn_resta;
    private javax.swing.JButton btn_suma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt_resultado;
    private javax.swing.JTextField txt_val1;
    private javax.swing.JTextField txt_val2;
    // End of variables declaration//GEN-END:variables
}
